services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - ./:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hive
      MYSQL_CHARSET: utf8mb4
    ports:
      - "3306:3306"
