services:
  app:
    build: ./Hive
    ports:
      - "8000:8000"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    volumes:
      - ./:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hive
      MYSQL_CHARSET: utf8mb4
    ports:
      - "3306:3306"
  ai:
    build: ./AI
    ports:
      - "6000:6000"