tool:
  sonarRunnerInstallation:
    installations:
      - name: "SonarScanner"
        home: "/var/jenkins_home/tools/"
        properties:
          - installSource:
              installers:
                - sonarRunnerInstaller:
                    id: "5.0.1.3006"
credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: "SonarScanner"
              secret: "mqdUwdOVrNmv9Ts0hbE73VrVmYW9d0B2deLbj0Wyvpg="
unclassified:
  sonarglobalconfiguration:
    buildWrapperEnabled: true
    installations:
      - name: "SonarScanner"
        serverUrl: "http://sonarqube:9000"
        credentialsId: "SonarScanner"
jobs:
  - script: >
      multibranchPipelineJob('HiveGame') {
        branchSources {
          git {
            id = 'github'
            remote('https://github.com/BastiaanMeijer2002/itvb23ows-starter-code.git')
          }
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep(20)
          }
        }
        factory {
          workflowBranchProjectFactory {
            scriptPath('Jenkinsfile')
          }
        }
      }
jenkins:
  authorizationStrategy: unsecured
  globalNodeProperties:
    - environmentVariables:
        env:
          - key: "SONAR_LOGIN"
            value: "jenkins"
          - key: "SONAR_PASSWORD"
            value: "jenkins"
